package ubpartner.logmanagement.commun;

/**
 * Class of properties file constant for printing log.
 */
public final class ConstantePrintLogProperties {
	
	/**
     * Empty constructor for the final class.
     */
    private ConstantePrintLogProperties() {
        // Class cannot be Instantiated.
    }

    /**
     * Set rootLogger key in properties file.
     */
    public static final String ROOTLOGGERPROP = "log4j.logger." + Constante.PRINTLOGGERNAME;

    /**
     * Set rootLogger key value in properties file.
     */
    public static final String ROOTLOGGERVALUE = "ALL, CONSOLE";

    /**
     * Set Console key in properties file.
     */
   public static final String CONSOLEPROP = "log4j.appender.CONSOLE";

   /**
    * Set Console key value in properties file.
    */
   public static final String CONSOLEVALUE = "org.apache.log4j.ConsoleAppender";

   /**
    * Set Console target key in properties file.
    */
   public static final String TARGETPROP = "log4j.appender.CONSOLE.Target";

   /**
    * Set Console target key value in properties file.
    */
   public static final String TARGETVALUE = "System.out";

   /**
    * Set Console layout key in properties file.
    */
   public static final String CONSOLELAYOUTPROP = "log4j.appender.CONSOLE.layout";

   /**
    * Set Console layout key value in properties file.
    */
   public static final String CONSOLELAYOUTVALUE = "org.apache.log4j.PatternLayout";

   /**
    * Set Console layout conversion pattern key in properties file.
    */
   public static final String CONVERSIONPATTERNPROP = "log4j.appender.CONSOLE.layout.ConversionPattern";

   /**
    * Set Console layout conversion pattern key value in properties file.
    */
   public static final String CONVERSIONPATTERNVALUE = "%d{ABSOLUTE} %5p %c{1}:%L - %m%n";

   /**
    * Set Console threshold key value in properties file.
    */
   public static final String CONSOLETHRESHOLDPROP = "log4j.appender.CONSOLE.Threshold";
   
   /**
    * Commentary when set values in configuration file.
    */
   public static final String SETCONFIGCOMMENT =
          "PrintLog.properties generated by LogManagement";

}
